### POST
POST http://localhost:3000/api

{
  "name": "John Doe"
}

### PUT
PUT http://localhost:3000/api

{
  "name": "John Doe"
}

### PATCH
PATCH http://localhost:3000/api

{
  "name": "John Doe"
}

### DELETE
DELETE http://localhost:3000/api

### OPTIONS
OPTIONS http://localhost:3000/api

### GET
GET http://localhost:3000/api

### HEAD
HEAD http://localhost:3000/api